from Backend.database import get_db_connection


def create_tables():
    with get_db_connection() as connection:

        # -------------------------
        # Enable pgvector
        # -------------------------

        connection.execute("""
            CREATE EXTENSION IF NOT EXISTS vector
        """)

        # -------------------------
        # Users
        # -------------------------

        connection.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id SERIAL PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                email VARCHAR(255) UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # -------------------------
        # Resume Batches
        # -------------------------

        connection.execute("""
            CREATE TABLE IF NOT EXISTS resume_batches (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL
                    REFERENCES users(id)
                    ON DELETE CASCADE,

                total_files INTEGER NOT NULL,
                processed_files INTEGER NOT NULL DEFAULT 0,
                successful_files INTEGER NOT NULL DEFAULT 0,
                failed_files INTEGER NOT NULL DEFAULT 0,

                status VARCHAR(20) NOT NULL DEFAULT 'pending',

                created_at TIMESTAMPTZ DEFAULT NOW(),
                completed_at TIMESTAMPTZ
            )
        """)

        # -------------------------
        # Candidates
        # -------------------------

        connection.execute("""
            CREATE TABLE IF NOT EXISTS candidates (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL
                    REFERENCES users(id)
                    ON DELETE CASCADE,

                name TEXT NOT NULL,
                email TEXT,
                resume_filename TEXT NOT NULL,
                resume_text TEXT NOT NULL,
                embedding VECTOR(768),

                created_at TIMESTAMPTZ DEFAULT NOW()
            )
        """)

        # Add batch_id to existing candidates table
        connection.execute("""
            ALTER TABLE candidates
            ADD COLUMN IF NOT EXISTS batch_id BIGINT
            REFERENCES resume_batches(id)
            ON DELETE SET NULL
        """)

        # -------------------------
        # Jobs
        # -------------------------

        connection.execute("""
            CREATE TABLE IF NOT EXISTS jobs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL
                    REFERENCES users(id)
                    ON DELETE CASCADE,

                title TEXT NOT NULL,
                description TEXT NOT NULL,
                embedding VECTOR(768),
                skills JSONB,
                keywords JSONB,

                created_at TIMESTAMPTZ DEFAULT NOW()
            )
        """)

        # -------------------------
        # Interview Questions
        # -------------------------

        connection.execute("""
            CREATE TABLE IF NOT EXISTS interview_questions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_id BIGINT NOT NULL
                    REFERENCES jobs(id)
                    ON DELETE CASCADE,

                question TEXT NOT NULL,
                answer TEXT NOT NULL,

                created_at TIMESTAMPTZ DEFAULT NOW()
            )
        """)

        # -------------------------
        # Indexes
        # -------------------------

        connection.execute("""
            CREATE INDEX IF NOT EXISTS candidates_embedding_idx
            ON candidates
            USING hnsw (embedding vector_cosine_ops)
        """)

        connection.execute("""
            CREATE INDEX IF NOT EXISTS jobs_embedding_idx
            ON jobs
            USING hnsw (embedding vector_cosine_ops)
        """)

        connection.execute("""
            CREATE INDEX IF NOT EXISTS resume_batches_user_id_idx
            ON resume_batches(user_id)
        """)

        connection.execute("""
            CREATE INDEX IF NOT EXISTS candidates_batch_id_idx
            ON candidates(batch_id)
        """)

        connection.commit()

    print("Database tables created successfully!")


if __name__ == "__main__":
    create_tables()